### ISSUE TITLE
Tarefas da Semana - S0

### ISSUE THREAD

**Issue by gabrielrosa09** [fga-eps-mds/2023.1-RelatorioGitPython#1]
- [x] Instalar o ambiente Linux nos computadores de cada membro.
- [x] Cada membro deve montar sua grade horária de horário livres.
- [x] Definir dia/hora da semana para o planejamento. 
- [x] Realizar quadro de conhecimento de cada membro.
- [x] Definir 3 temas em ordem de interesses

**Comment by gabrielrosa09** [comment]
Planilha com os horários de cada integrantes e o quadro de conhecimento
https://docs.google.com/spreadsheets/d/1UfNvdiX7npMij5zfJx7sF0S9yFon2dlrtVmWwM5wxIM/edit#gid=431366674

**Comment by lucaslobao-18** [comment]
## 1 - Robô de monitoramento dos videos assistidos no moodle

Com base em uma votação do grupo e todos os temas disponíveis, o que mais nos chamou atenção foi o de fazer um bot para monitorar os usuários na utilização do moodle. Com ele conseguiriamos obter informações como: Por quanto tempo um aluno permaneceu na plataforma, quais conteúdos foram acessados, quantos logins foram feitos... entre outras coisas.

## 2 - Biblioteca em Python para gerar relatório de repositório git

Esse foi o segundo tema mais votado, um programa que será capaz de analizar repositórios e gerar relatórios, tanto sobre o repositório como sobre o usuário, por exemplo, quantidade de issues fechadas na semana, de commits por semana e por aí vai.

## 3 - Análise de dados de desistência matérias FGA

Utilize dados de desistência dos estudantes no Moodle para identificar fatores que influenciam na desistência e desenvolver modelos de previsão de desistência dos estudantes.
