### ISSUE TITLE
Reunião com o Léo sobre os requisitos

### ISSUE THREAD

**Issue by GZaranza** [fga-eps-mds/2023.1-RelatorioGitPython#17]
## Descrição do Problema
Precisamos nos aprofundar sobre o tema e os requisitos

## Solução Proposta
Marcar uma reunião com o Léo, pois ele pode nos ajudar com esse problema

## Tarefas
  - [x] Marcar reunião 

  - [x] Fazer a reunião

  - [x] Fazer uma ata da reunião

## Critérios de Aceitação
  - [x] Reunião realizada

  - [x] Passar para a equipe o que foi discutido na reunião

**Comment by catlenc** [comment]
## Ata da Reunião

- Participaram da reunião Catlen, Gabriel Rosa e Lucas.

- A reunião teve como principal objetivo conversar com o cliente, o Leo,  para definirmos quais os requisitos do projeto.

- Ficou definido que será feito uma biblioteca que a partir do repositório local gere insumos nos dados a partir do git-log e da pasta .git.

- O trabalho deverá ser feito via offline.

- O cliente sugeriu que fossem utilizados o Python e o poetry.

- O Leo também falou da importância de aprendermos sobre o github, git-log e Python
