### ISSUE TITLE
Estudar Venv

### ISSUE THREAD

**Issue by gabrielrosa09** [fga-eps-mds/2023.1-RelatorioGitPython#19]
## Descrição do Problema
Precisamos estudar como criar um ambiente para todos a partir do pyenv para substituir o Docker.

## Solução Proposta
Estudar Pyenv e colocar informações de configuração do ambiente.

## Tarefas
  - [x] Estudar Pyenv.

  - [x] Explicação de como configurar o pyenv.

## Critérios de Aceitação
  - [x] Todos conseguirem configurar o pyenv.

## Recursos

 - Youtube.
 - Documentação do Pyenv.

**Comment by GZaranza** [comment]
Conversando com o Léo, é melhor usar o venv do que o pyenv

**Comment by ViniciussdeOliveira** [comment]
# Como criar um ambiente virtual
Para utilizar o ambiente virtual venv primeiro devemos verificar se a versão do python que estamos utilizando é igual ou superior a versão 3.4. Para consultar abra o seu terminal e digite:<br>

python --version<br>

Estando com a versão certa do python vá até o diretório que deseja criar o ambiente virtual e digite:<br>

(No windows): python -m venv nome_do_ambiente_virtual<br>
(No linux): python3 -m venv nome_do_ambiente_virtual<br>

O processo para criar um ambiente virtual pode demorar um pouco, mas depois de criado é so ativar digitando o seguinte comando dentro do diretorio:<br>

(No windows): nome_do_ambiente_virtual\scripts\activate.bat<br>
(No linux): source nome_do_ambiente_virtual/bin/activate<br>

Para desativar digite:<br>
deactivate
