### ISSUE TITLE
Definição de épicos, features e estórias de usuário 

### ISSUE THREAD

**Issue by GZaranza** [fga-eps-mds/2023.1-RelatorioGitPython#28]
## Descrição do Problema
Definir os Épicos, Features e estórias do projeto

## Solução Proposta
Elaboração do diagrama

## Tarefas
  - [X] Definição dos Épicos

  - [X] Definição das Features

  - [X] Definição das Estórias
  
  - [X]  Elaboração do StoryMap

## Critérios de Aceitação
  - [X] StoryMap Concluído no Mirro

## Recursos

 - Estudo para o assunto disponível no material enviado pela professora

**Comment by lucaslobao-18** [comment]
[Link do StoryMap](https://miro.com/app/board/uXjVMQBxfUA=/)
