### ISSUE TITLE
Função que liste as extensões de arquivos commitados

### ISSUE THREAD

**Issue by GZaranza** [fga-eps-mds/2023.1-RelatorioGitPython#35]
## Descrição do Problema
Precisamos de um função que liste todas as extensões de arquivos commitados.

## Solução Proposta
 será feito uma nova branch com a função que identifica e lista as extensões de cada aquivo do repositório. Essa função será feita em linguagem python e gerará com saída um arquivo em markdown

## Tarefas
  - [X] criar a função em dupla

  - [X] testar a saída

  - [x] criar uma branche com o nome da função
  
  - [x] Commitar a função dentro da branche 

## Critérios de Aceitação
  - [X] gerar um arquivo em markdown com uma tabela contendo o nome do autor e seus respectivos nomes e tipos de cada arquivo commitado

**Comment by catlenc** [comment]
> será feito uma nova branch com a função que identifica e lista as extensões de cada aquivo do repositório

**Comment by FelipeDireito** [comment]
Ficou fera demais!
