### ISSUE TITLE
Estudar empacotamento de biblioteca 

### ISSUE THREAD

**Issue by GZaranza** [fga-eps-mds/2023.1-RelatorioGitPython#43]
## Descrição do Problema
Precisamos saber como empacotar uma biblioteca python.

## Solução Proposta

Estudar e descrever quais os requisitos para publicar uma biblioteca.

## Tarefas
  - [x] Estudar o funcionamento de bibliotecas no pypi.

  - [x]  Documentar os requisitos.

**Comment by FelipeDireito** [comment]
# Resumo dos requisitos

- 1.  É preciso criar uma conta no PyPI.
- 2. Ter um README e um LICENSE na pasta principal do repositório atualizados.
- 3. Confirgurar os *setuptools*, devendo conter um arquivo chamado ***setup.py*** que descreva sua biblioteca, suas dependências e outras informações relevantes, como informações de quem publicou e o nome da biblioteca.
- 4. A ferramenta mais utilizada para publicar é o **'twine'**, diretamente pelo terminal.
